In [5]:
#1번문제
import math

def powerK(n):
    return int(math.log(n, 2))

In [6]:
print(powerK(10))

3


In [7]:
print(powerK(50))

5


In [9]:
print(powerK(1025))

10


In [20]:
#2번문제

def isCircleWord(w):
    isCw = True 
    for i in range(len(w) // 2):      
        if w[i] != w[-1 - i]:      
            isCw = False
            return isCw
            break
    return isCw

In [23]:
print(isCircleWord("level"))

True


In [24]:
print(isCircleWord("ohhh"))

False


In [34]:
#3번문제

#답:5

In [96]:
#4번문제
def binaryS(l,wanna,left,right):
    m_idx = (left+right)//2
    m = l[m_idx]
    if wanna == m:
        print("m_idx:{0}, find num:{1}".format(m_idx,l[m_idx]))
        
    elif m > wanna:
        binaryS(l, wanna,left,m_idx-1)
        
    elif wanna > m:
        binaryS(l, wanna,m_idx+1,right)
    

In [97]:
l=[12, 34, 37, 45 ,57, 82, 99, 120 ,134]
binaryS(l,120,0,len(l)-1)


m_idx:7, find num:120


In [3]:
#5번문제
import numpy as np

arr=np.array(range(25)).reshape((5,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
def rotate(m):
    
    ret = [[0] * 5for _ in range(5)]
    for r in range(5):
        for c in range(5):
            ret[c][5-1-r] = m[r][c]
    return ret

In [8]:
print(np.array(rotate(arr)))

[[20 15 10  5  0]
 [21 16 11  6  1]
 [22 17 12  7  2]
 [23 18 13  8  3]
 [24 19 14  9  4]]


In [10]:
#6번문제

def pairSum(l,a):
    lenth=len(l)
    answer=[]
    for i in range(lenth-1):
        for j in range(i+1,lenth):
            if l[i]+l[j]==a:
                answer.append('{0}+{1}'.format(l[i],l[j]))
            
    return answer
    

In [11]:
inputarr=[2,4,3,5,6,-2,4,7,8,9]
pairSum(inputarr,7)

['2+5', '4+3', '3+4', '-2+9']